import { useEffect, useState } from "react";
import { Link, useSearchParams } from "react-router-dom";
import client from "../api/client";

export default function AgentDashboard() {
  const [params, setParams] = useSearchParams(); const [data, setData] = useState({ items: [], total: 0, page: 1, page_size: 20 }); const [search, setSearch] = useState(params.get("q") || ""); const [error, setError] = useState("");
  const status = params.get("status") || ""; const category = params.get("category") || ""; const priority = params.get("priority") || ""; const page = Number(params.get("page") || 1);
  useEffect(() => { const timer = setTimeout(() => { const query = new URLSearchParams(params); if (search) query.set("q", search); else query.delete("q"); query.set("page", "1"); setParams(query); }, 300); return () => clearTimeout(timer); }, [search]);
  useEffect(() => { client.get(`/api/tickets?${params.toString()}`).then(({ data: next }) => setData(next)).catch(() => setError("Unable to load tickets")); }, [params]);
  const setFilter = (key, value) => { const next = new URLSearchParams(params); if (value) next.set(key, value); else next.delete(key); next.set("page", "1"); setParams(next); };
  return <section className="content wide"><div className="eyebrow">AGENT SPACE / TICKETS</div><h1>Ticket queue.</h1><div className="filter-bar"><select value={status} onChange={(e) => setFilter("status", e.target.value)}><option value="">All statuses</option><option>Open</option><option>Resolved</option></select><select value={category} onChange={(e) => setFilter("category", e.target.value)}><option value="">All categories</option>{["IT", "HR", "Finance", "Admin", "Other"].map((value) => <option key={value}>{value}</option>)}</select><select value={priority} onChange={(e) => setFilter("priority", e.target.value)}><option value="">All priorities</option>{["Low", "Medium", "High"].map((value) => <option key={value}>{value}</option>)}</select><input placeholder="Search titles" value={search} onChange={(e) => setSearch(e.target.value)} /></div>{error && <p className="error">{error}</p>}<div className="table-wrap"><table><thead><tr><th>Title</th><th>Employee</th><th>Category</th><th>Priority</th><th>Status</th><th>Created</th></tr></thead><tbody>{data.items.map((ticket) => <tr key={ticket.id}><td><Link to={`/tickets/${ticket.id}`}>{ticket.title}</Link></td><td>{ticket.employee.email}</td><td><span className="chip">{ticket.ai_category}</span></td><td><span className="chip">{ticket.ai_priority}</span></td><td><span className={`badge ${ticket.status.toLowerCase()}`}>{ticket.status}</span></td><td>{new Date(ticket.created_at).toLocaleDateString()}</td></tr>)}</tbody></table>{!data.items.length && <div className="empty-card">No matching tickets.</div>}</div><div className="pagination"><button disabled={page <= 1} onClick={() => setFilter("page", String(page - 1))}>Previous</button><span>Page {data.page} of {Math.max(1, Math.ceil(data.total / data.page_size))}</span><button disabled={page >= Math.ceil(data.total / data.page_size)} onClick={() => setFilter("page", String(page + 1))}>Next</button></div></section>;
}
