import { useEffect, useRef, useState } from "react";
import { useParams } from "react-router-dom";
import client from "../api/client";

export default function TicketDetail() {
  const { id } = useParams(); const [ticket, setTicket] = useState(null); const [draft, setDraft] = useState(""); const [citations, setCitations] = useState([]); const [finalCategory, setFinalCategory] = useState(""); const [finalPriority, setFinalPriority] = useState(""); const [loading, setLoading] = useState(false); const [error, setError] = useState(""); const [confirmation, setConfirmation] = useState(""); const editor = useRef(null);
  const loadTicket = () => client.get(`/api/tickets/${id}`).then(({ data }) => { setTicket(data); setDraft(data.ai_draft || ""); setCitations(data.ai_citations || []); setFinalCategory(data.final_category); setFinalPriority(data.final_priority); }).catch((err) => setError(err.response?.data?.detail || "Unable to load ticket"));
  useEffect(() => { loadTicket(); }, [id]);
  useEffect(() => { if (editor.current) { editor.current.style.height = "auto"; editor.current.style.height = `${editor.current.scrollHeight}px`; } }, [draft]);
  const generate = async () => { setLoading(true); setError(""); try { const { data } = await client.post(`/api/tickets/${id}/ai-draft`); setDraft(data.ai_draft); setCitations(data.citations); } catch (err) { setError(err.response?.data?.detail || "Unable to generate draft"); } finally { setLoading(false); } };
  const saveOverride = async () => { setLoading(true); setError(""); setConfirmation(""); try { await client.patch(`/api/tickets/${id}/classification`, { final_category: finalCategory, final_priority: finalPriority }); await loadTicket(); setConfirmation("Override logged"); } catch (err) { setError(err.response?.data?.detail || "Unable to save override"); } finally { setLoading(false); } };
  const send = async () => { setLoading(true); try { const { data } = await client.post(`/api/tickets/${id}/reply`, { reply_text: draft }); setTicket(data); } catch (err) { setError(err.response?.data?.detail || "Unable to send reply"); } finally { setLoading(false); } };
  if (error && !ticket) return <section className="content"><p className="error">{error}</p></section>; if (!ticket) return <div className="loading">Loading ticket...</div>;
  const overridden = ticket.final_category !== ticket.ai_category || ticket.final_priority !== ticket.ai_priority;
  return <section className="content wide"><div className="eyebrow">TICKET / DETAIL</div><div className="detail-heading"><h1>{ticket.title}</h1><span className={`badge ${ticket.status.toLowerCase()}`}>{ticket.status}</span></div><div className="detail-card"><h2>Original ticket</h2><p>{ticket.description}</p><div className="detail-grid"><span><b>Employee</b>{ticket.employee.email}</span><span><b>Created</b>{new Date(ticket.created_at).toLocaleString()}</span><span><b>Attachment</b>{ticket.attachment_filename || "None"}</span></div></div><div className="detail-card"><h2>Classification</h2><p className="muted">{overridden ? <>Overridden · AI suggested {ticket.ai_category} / {ticket.ai_priority}</> : "AI-suggested"}</p><div className="override-controls"><select value={finalCategory} onChange={(e) => setFinalCategory(e.target.value)}>{["IT", "HR", "Finance", "Admin", "Other"].map((value) => <option key={value}>{value}</option>)}</select><select value={finalPriority} onChange={(e) => setFinalPriority(e.target.value)}>{["Low", "Medium", "High"].map((value) => <option key={value}>{value}</option>)}</select><button className="secondary" disabled={loading} onClick={saveOverride}>Save override</button></div>{!ticket.ai_classified && <p className="muted">AI unavailable — default used</p>}{confirmation && <p className="confirmation">{confirmation}</p>}</div><div className="detail-card"><h2>Override history</h2>{ticket.audit_log?.length ? <div className="audit-list">{ticket.audit_log.map((entry) => <div key={entry.id}>{entry.agent.email} changed {entry.field} {entry.from_value} → {entry.to_value} · {new Date(entry.created_at).toLocaleString()}</div>)}</div> : <p className="muted">No overrides logged.</p>}</div>{ticket.status === "Open" ? <><div className="detail-card"><div className="section-heading"><h2>Draft reply</h2><button className="secondary" onClick={generate} disabled={loading}>{loading ? "Working..." : "Generate AI draft"}</button></div><textarea ref={editor} className="draft-editor" value={draft} onChange={(e) => setDraft(e.target.value)} placeholder="Generate a draft or write a reply" />{citations.length ? <div className="citations">{citations.map((citation) => <span className="chip" key={citation.article_id}>{citation.title}</span>)}</div> : <p className="muted">No knowledge base article matched — draft is ungrounded.</p>}</div><div className="send-row"><button className="primary" disabled={!draft.trim() || loading} onClick={send}>Send reply</button></div></> : <><div className="detail-card"><h2>Final reply</h2><p>{ticket.final_reply}</p></div>{(draft || ticket.ai_draft) ? <div className="detail-card"><h2>AI draft (for comparison)</h2><p className="draft-readonly">{draft || ticket.ai_draft}</p>{citations.length ? <div className="citations">{citations.map((citation) => <span className="chip" key={citation.article_id}>{citation.title}</span>)}</div> : null}</div> : null}</>}{error && <p className="error">{error}</p>}</section>;
}
