import { useEffect, useRef, useState } from "react";
import { useParams } from "react-router-dom";
import client from "../api/client";

export default function TicketDetail() {
  const { id } = useParams(); const [ticket, setTicket] = useState(null); const [draft, setDraft] = useState(""); const [citations, setCitations] = useState([]); const [loading, setLoading] = useState(false); const [error, setError] = useState(""); const editor = useRef(null);
  useEffect(() => { client.get(`/api/tickets/${id}`).then(({ data }) => { setTicket(data); setDraft(data.ai_draft || ""); setCitations(data.ai_citations || []); }).catch((err) => setError(err.response?.data?.detail || "Unable to load ticket")); }, [id]);
  useEffect(() => { if (editor.current) { editor.current.style.height = "auto"; editor.current.style.height = `${editor.current.scrollHeight}px`; } }, [draft]);
  const generate = async () => { setLoading(true); setError(""); try { const { data } = await client.post(`/api/tickets/${id}/ai-draft`); setDraft(data.ai_draft); setCitations(data.citations); } catch (err) { setError(err.response?.data?.detail || "Unable to generate draft"); } finally { setLoading(false); } };
  const send = async () => { setLoading(true); try { const { data } = await client.post(`/api/tickets/${id}/reply`, { reply_text: draft }); setTicket(data); } catch (err) { setError(err.response?.data?.detail || "Unable to send reply"); } finally { setLoading(false); } };
  if (error && !ticket) return <section className="content"><p className="error">{error}</p></section>; if (!ticket) return <div className="loading">Loading ticket...</div>;
  return <section className="content wide"><div className="eyebrow">TICKET / DETAIL</div><div className="detail-heading"><h1>{ticket.title}</h1><span className={`badge ${ticket.status.toLowerCase()}`}>{ticket.status}</span></div><div className="detail-card"><h2>Original ticket</h2><p>{ticket.description}</p><div className="detail-grid"><span><b>Employee</b>{ticket.employee.email}</span><span><b>Created</b>{new Date(ticket.created_at).toLocaleString()}</span><span><b>Attachment</b>{ticket.attachment_filename || "None"}</span></div></div><div className="detail-card"><h2>AI suggestion <small>AI-suggested</small></h2><div className="ticket-meta"><span className="chip">{ticket.ai_category}</span><span className="chip">{ticket.ai_priority}</span></div>{!ticket.ai_classified && <p className="muted">AI unavailable — default used</p>}</div>{ticket.status === "Open" ? <><div className="detail-card"><div className="section-heading"><h2>Draft reply</h2><button className="secondary" onClick={generate} disabled={loading}>{loading ? "Working..." : "Generate AI draft"}</button></div><textarea ref={editor} className="draft-editor" value={draft} onChange={(e) => setDraft(e.target.value)} placeholder="Generate a draft or write a reply" />{citations.length ? <div className="citations">{citations.map((citation) => <span className="chip" key={citation.article_id}>{citation.title}</span>)}</div> : <p className="muted">No knowledge base article matched — draft is ungrounded.</p>}</div><div className="send-row"><button className="primary" disabled={!draft.trim() || loading} onClick={send}>Send reply</button></div></> : <div className="detail-card"><h2>Final reply</h2><p>{ticket.final_reply}</p></div>}{error && <p className="error">{error}</p>}</section>;
}
